### ISSUE TITLE
Architektur ViewModel vs. Entity

### ISSUE THREAD

**Issue by StephGit** [StephGit/EazyTime#4]
Engineering!

**Comment by StephGit** [comment]
## Use ViewModel instead of entities
### Pro:

* Kein Verlust von state bei Konfigurationsänderungen (bsp. Device Rotation), ViewModel überlebt!
* Datenherkunft ist nicht relevant (Room, external DB)
* Separation of concerns
* Testbarkeit wird 

[](https://developer.android.com/topic/libraries/architecture/images/final-architecture.png)

**Comment by ChristianMuellerBE** [comment]
https://www.youtube.com/watch?v=T-nQP9fidKU

Hier noch ein Tutorial für Data Binding with LiveData (Two-way & One-way):
* 2-way-databinding
*  MutableLiveData

**Comment by StephGit** [comment]
https://www.techyourchance.com/dependency-injection-viewmodel-with-dagger-2/

**Comment by StephGit** [comment]
https://medium.com/@fabioCollini/android-testing-using-dagger-2-mockito-and-a-custom-junit-rule-c8487ed01b56

**Comment by StephGit** [comment]
https://github.com/googlesamples/android-architecture-components/blob/74b2afe88fd79c37361120e3cb454561687a853d/GithubBrowserSample/app/src/main/java/com/android/example/github/repository/NetworkBoundResource.java
