### ISSUE TITLE
Gesamtzeit auf Kanender-Detail wird falsch berechnet.

### ISSUE THREAD

**Issue by ChristianMuellerBE** [StephGit/EazyTime#63]
Gesamtzeit auf Kalender-Liste stimmt, im Detail nicht

**Comment by StephGit** [comment]
Gesamtzeit stimmt auf Kalender-List und Detail nicht. 
![Screenshot_1552835058](https://user-images.githubusercontent.com/24672636/54493329-04f36180-48cf-11e9-9779-1b64bf98974b.png)

Möglicherweise ein Zusammenhang mit dem Counter. Wenn ich bspw. kurz nachdem Wechsel auf 10 Sekunden klicke, springt der Counter auf 9 zurück
